### ISSUE TITLE
mesh file for x_arm_musculoskeletal

### ISSUE THREAD

**Issue by jiye33** [et0803/memikrr#1]
Hi. I'm testing this package to find out natural configuration of human arm.
I want to visualize the result but I don't know where can I get mesh file for it.
Where can I get stl file?
Thank you.

**Comment by et0803** [comment]
Hi there, the mesh files are in [stl.zip](https://github.com/user-attachments/files/16708053/stl.zip).

They are mainly converted from the vtp files in an opensim project [Upper Extremity Dynamic Model](https://simtk.org/projects/upexdyn). 

Also an matlab program is provided for visualization test.

Please notice that the mesh files are standard ones without scaling.

**Comment by jiye33** [comment]
Thanks a lot!
